module.exports = [
'10th Kingdom, The',
'10 Things I Hate About You',
'12 Years a Slave',
'127 Hours',
'13 Going on 30',
'13th Warrior, The',
'1408',
'17 Again',
'1941',
'1969',
'20,000 Leagues Under the Sea',
'2001: A Space Odyssey',
'2010: The Year We Make Contact',
'2012',
'2046',
'21 Grams',
'25th Hour',
'27 Dresses',
'28 Days Later',
'28 Weeks Later',
'3 Idiots',
'300',
'3000 Miles to Graceland',
'3:10 to Yuma',
'40 Year-Old Virgin, The',
'400 Blows, The',
'50/50',
'50 First Dates',
'500 Days of Summer',
'7 Pounds',
'8 Mile',
'About Last Night...',
'About Schmidt',
'About Time',
'Abraham Lincoln: Vampire Hunter',
'Absence of Malice',
'Accidental Tourist, The',
'Accused, The ',
'Ace Ventura: Pet Detective',
'Ace Ventura: When Nature Calls',
'Across the Universe',
'Act of Valor',
'Adam\'s Rib',
'Addams Family, The',
'Adjustment Bureau, The',
'The Adventures of Pinocchio ',
'Adventures of Robin Hood, The',
'Adventures of Tintin, The',
'The Affair of the Necklace',
'After Hours',
'After Sex',
'Aguirre, the Wrath of God',
'A.I. Artificial Intelligence',
'Air Bud',
'Air Force One',
'Airplane!',
'Airplane II: The Sequel',
'Airport',
'Airport 1975',
'Airport \'77',
'Akeelah and the Bee',
'Akira',
'Aladdin',
'Aladdin and the King of Thieves',
'The Alamo ',
'Albatross',
'Alexander',
'Alice Doesn\'t Live Here Anymore',
'Alice in Wonderland ',
'Alice in Wonderland ',
'Alice in Wonderland ',
'Alien',
'Aliens',
'Alien 3',
'Aliens in the Attic',
'Alive',
'All About My Mother',
'All About Steve',
'Almost Heroes',
'Alvin and the Chipmunks',
'Alvin and the Chipmunks: The Squeakquel',
'Alvin and the Chipmunks: Chipwrecked',
'All About Steve',
'All Dogs Go to Heaven',
'All Dogs Go to Heaven 2',
'All of Me',
'All the President\'s Men',
'All the Right Moves',
'Almost Famous',
'Along Came a Spider',
'Alpha Dog',
'Alpha and Omega',
'The Amazing Spider-Man ',
'The Amazing Spider-Man 2',
'The Amityville Horror ',
'American Beauty',
'American Chai',
'American Gangster',
'American Graffiti',
'American History X',
'American in Paris, An',
'American Me',
'American Pie',
'American Pie 2',
'American Pie Presents: The Book Of love',
'American Psycho',
'American Reunion',
'American Sniper',
'American Tail, An',
'American Tail: Fievel Goes West, An',
'An American Tail: The Treasure of Manhattan Island',
'American Wedding',
'Americanization of Emily, The',
'Animal Farm',
'Amistad',
'Amour ',
'Analyze This',
'Anastasia',
'Anchorman 2: The Legend Continues',
'Anchorman: The Legend of Ron Burgundy',
'...And Justice For All',
'And the Band Played On',
'Angel Eyes',
'Angel Heart',
'Angels & Demons',
'Angels in the Outfield',
'Angels with Dirty Faces',
'Angus, Thongs and Perfect Snogging',
'Animal House',
'Anna and the King',
'Anna Karenina',
'Annie',
'Annie Hall',
'Another Cinderella Story',
'Antitrust',
'Antz',
'Apocalypse Now',
'Apocalypto',
'Apollo 13',
'Are We Done Yet?',
'Are We There Yet?',
'Argo',
'Aristocats, The',
'Armageddon',
'Around the World in 80 Days ',
'Arsenic and Old Lace',
'Arthur',
'As Good As It Gets',
'Assassination Games',
'Assassination of a High School President',
'At First Sight',
'Atlantic City',
'Atlantis: The Lost Empire',
'Atonement',
'Attack of the 50 Foot Woman',
'August Rush',
'Austin Powers: International Man of Mystery',
'Austin Powers: The Spy Who Shagged Me',
'Austin Powers in Goldmember',
'Avatar',
'The Avengers ',
'Aviator, The',
'Away from Her',
'Babe',
'Babe, The',
'Babylon A.D',
'Bachelor Mother',
'Bachelorette',
'Backdraft',
'Back to the Future',
'Back to the Future Part II',
'Back to the Future Part III',
'Back to School',
'Bad and the Beautiful, The',
'Bad Boys ',
'Bad Boys II',
'Bad Day at Black Rock',
'Bad Santa',
'Bad Taste',
'Badlands',
'Balto',
'Bambi',
'Bambi II',
'Bananas',
'Barbarella',
'Barcelona',
'Barton Fink',
'Barry Lyndon',
'BASEketball',
'Basic Instinct',
'Basic Instinct 2',
'Batman ',
'Batman Begins',
'Batman Forever',
'Batman Returns',
'Battle: Los Angeles',
'Battle of San Pietro, The',
'Battle Royale',
'Beach, The',
'Beaches',
'Bean ',
'Beast of Yucca Flats, The',
'Beasts of the Southern Wild',
'Beau Geste ',
'Beautiful Girls',
'Beautiful Mind, A',
'Beautiful Thing ',
'Beauty and the Beast ',
'Beavis and Butthead Do America',
'Becoming Jane',
'Bedazzled ',
'Bedazzled ',
'Bedknobs and Broomsticks',
'Bedtime Stories',
'Bee Movie',
'Bee Season',
'Beerfest',
'Beetlejuice',
'Before Midnight',
'Before Sunrise',
'Before Sunset',
'Beginners',
'Behind Enemy Lines',
'Being John Malkovich',
'Behind the Candelabra',
'Being There',
'Be Kind Rewind',
'Believer, The',
'Ben-Hur ',
'Bend It Like Beckham',
'Benny & Joon',
'Beowulf',
'Best Little Whorehouse in Texas, The',
'Best in Show',
'Best Years of Our Lives, The',
'Better Off Dead',
'Better Than Chocolate',
'Better Tomorrow, A',
'Beverly Hills Chihuahua',
'Beverly Hills Cop II',
'Beverly Hills Cop III',
'Beyond the Valley of the Dolls',
'Bicentennial Man',
'Bicycle Thieves',
'Big',
'Big Chill, The',
'Big Daddy',
'Big Easy, The',
'Big Fat Liar',
'Big Fish',
'Big Hero 6',
'Big Lebowski, The',
'Big Night',
'Big Sleep, The ',
'Big Top Pee-wee',
'Big Trouble',
'Big Trouble in Little China',
'Bill and Ted\'s Excellent Adventure',
'Billy Madison',
'Birds, The',
'Birdman',
'Black Book',
'Black Cat, The ',
'Black Christmas ',
'Black Christmas ',
'Black Hawk Down',
'Black Hole, The',
'Black Rain',
'Black Sheep',
'Black Swan',
'Blade',
'Blade II',
'Blade: Trinity',
'Blade Runner',
'Blades of Glory',
'Blair Witch Project, The',
'Blind Date ',
'Blazing Saddles',
'Blood Diamond',
'Blood Feast',
'Blood Simple',
'Blow',
'Blown Away ',
'Blue Collar',
'Blue Jasmine',
'Blue Velvet',
'Blue Lagoon, The',
'Blues Brothers, The',
'Blues Brothers 2000',
'Body Heat',
'Body of Lies',
'Boiler Room',
'Bolt ',
'Boogeyman',
'Book of Life, The',
'Book of Pooh: Stories from the Heart, The',
'Book of Shadows: Blair Witch 2',
'Book Thief, The',
'Boondock Saints, The',
'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan',
'Born on the Fourth of July',
'Bottle Rocket',
'Bound',
'Bourne Identity, The',
'Bourne Legacy, The',
'Bourne Supremacy, The',
'Bourne Ultimatum, The',
'Bowling for Columbine',
'Boy Named Charlie Brown, A',
'Boyhood',
'Boys from Brazil, The',
'Boys Town',
'Boyz n the Hood',
'Braindead',
'Brassed Off',
'Brave',
'Braveheart',
'Brazil',
'Breakfast at Tiffany\'s',
'Breakfast Club, The',
'Breaking Away',
'Breaking Up',
'Brian\'s Song',
'Bride Wars',
'Bridge on the River Kwai, The',
'Bridge to Terabithia',
'Bridget Jones\'s Diary',
'Bring It On',
'Bringing Up Baby',
'Broadcast News',
'Brokeback Mountain',
'Broken Arrow',
'Bronx Tale, A',
'Brother Bear',
'Brother Bear 2',
'Brothers Grimm, The',
'Brothers McMullen, The',
'Brothers Solomon, The',
'Brubaker',
'Bruce Almighty',
'Buckaroo Banzai',
'Bucket List, The',
'Buffalo 66',
'Buffy the Vampire Slayer',
'Bug',
'Bug\'s Life, A',
'Bull Durham',
'Bullitt',
'Burn After Reading',
'But I\'m a Cheerleader',
'Butch Cassidy and the Sundance Kid',
'Butterfly Effect, The',
'By Dawn\'s Early Light',
'Cabin in the Woods, The',
'Cabinet of Dr. Caligari, The',
'Cable Guy, The',
'Caddyshack',
'Caine Mutiny, The',
'Camelot',
'Camille ',
'Camp Rock',
'Can\'t Buy Me Love',
'Can\'t Hardly Wait',
'Candy',
'Cape Fear (1apricorn One',
'Captain America: The First Avenger',
'Captain America: The Winter Soldier',
'Captain Phillips',
'Care Bears Movie, The',
'Care Bears Movie II: A New Generation',
'Carlito\'s Way',
'Carnal Knowledge',
'Carrie ',
'Carrie ',
'Cars',
'Cars 2',
'Casablanca',
'Casanova',
'Casino',
'Casino Royale',
'Cast Away',
'Casualties of War',
'Cat in the Hat, The ',
'Cat on a Hot Tin Roof',
'Cat People',
'Cat Returns, The',
'Catch-22',
'Catch Me If You Can',
'Cats & Dogs',
'Cats & Dogs: The Revenge of Kitty Galore',
'Cats Don\'t Dance',
'Catwoman',
'Cecil B. Demented',
'Changing Lanes',
'Charlie and the Chocolate Factory  (for the 1971 film, see Willy Wonka & the Chocolate Factory)',
'Charlie\'s Angels',
'Charlie\'s Angels: Full Throttle',
'Charlie Wilson\'s War',
'Chariots of Fire',
'Charlotte\'s Web ',
'Chasing Amy',
'Chasing Liberty',
'Cheaper by the Dozen ',
'Cheaper by the Dozen ',
'Cheaper by the Dozen 2',
'Cheech & Chong\'s Next Movie',
'Chicago',
'Chicken Run',
'Children of Dune',
'Children of Men',
'Children of Paradise',
'Children\'s Hour, The',
'Child\'s Play',
'Chinatown',
'Chitty Chitty Bang Bang',
'Chloe',
'Chocolat',
'Choke',
'Christmas Carol, A ',
'Christmas Story, A',
'Christmas with the Kranks',
'Chronicles of Narnia: Prince Caspian, The',
'Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The',
'Chronicles of Narnia: The Voyage of the Dawn Treader, The',
'Chronicles of Riddick, The',
'Chumscrubber, The',
'Chungking Express',
'Cider House Rules, The',
'Cinderella ',
'Cinderella Story, A',
'Citizen Kane',
'City of Angels',
'City of Ember',
'City on Fire',
'City of God',
'City Slickers',
'Clash of the Titans ',
'Clear and Present Danger',
'Cleopatra ',
'Click',
'Client, The',
'Clerks',
'Clerks II',
'Clockwise',
'Clockwork Orange, A',
'Close Encounters Of The Third Kind',
'Closer',
'Cloudy with a Chance of Meatballs',
'Cloudy with a Chance of Meatballs 2',
'Cloverfield',
'Clue',
'Clueless',
'Coach Carter',
'Cocktail',
'Color Purple, The',
'Cold Mountain',
'Collateral',
'Coming Home',
'Commando',
'Commitments, The',
'Compulsion',
'Con Air',
'Conan the Barbarian',
'Conan the Destroyer ',
'Coneheads',
'Confessions of a Dangerous Mind',
'Confetti',
'Conquest of Space',
'Conspiracy Theory',
'Constant Gardener, The',
'Constantine',
'Control ',
'Cool and the Crazy‎',
'Cool Hand Luke',
'Cool Runnings',
'Cool World',
'Cop and a Half',
'Coraline',
'Core, The',
'Corpse Bride',
'Contact',
'Court Jester, The',
'Count of Monte Cristo, The',
'Cowboy Bebop: The Movie',
'Coyote Ugly',
'Craft, The',
'Crank',
'Crash ',
'Crimes and Misdemeanors',
'Crimewave',
'Crimson Tide',
'Criss Cross',
'Crocodile Dundee',
'The Croods',
'Cross of Iron',
'Crouching Tiger, Hidden Dragon',
'Crow, The',
'Crow: City Of Angels, The',
'Cry Freedom',
'Cry Wolf',
'Cruel Intentions',
'Crying Game, The',
'Cube',
'Cube 2: Hypercube',
'Cube Zero',
'Cure, The ',
'The Curious Case of Benjamin Button',
'Curious George',
'Cursed ',
'Cutting Edge, The',
'Da Vinci Code, The',
'Daddy Day Camp',
'Daddy Day Care',
'Dallas Buyers Club',
'Dan in Real Life',
'Dance of the Dead',
'Dancer In The Dark',
'Dances with Wolves',
'Dangerous Beauty',
'Daredevil',
'Darjeeling Limited, The',
'Dark City',
'Dark Knight, The',
'Dark Knight Rises, The',
'Dark Passage',
'Dark Side of the Moon, The ',
'Das Boot',
'Das Leben der Anderen',
'Dave',
'Dawn of the Dead ',
'Dawn of the Dead ',
'Day After Tomorrow, The',
'Day at the Races, A',
'Day of the Jackal, The',
'Day the Earth Stood Still, The ',
'Day the Earth Stood Still, The ',
'Daydream Nation',
'Days of Being Wild',
'Days of Thunder',
'Dazed and Confused',
'Dead Alive',
'Dead Man Walking',
'Dead Poets Society',
'Deadfall',
'Death Becomes Her',
'Death Race',
'Death Rides a Horse',
'Death to Smoochy',
'Death Wish (I-V)',
'D.E.B.S.',
'Dedication',
'Deep Impact',
'Deep Throat',
'Deer Hunter, The',
'Deewar',
'Defending Your Life',
'Defendor',
'Déjà Vu ',
'Deliverance',
'Departed, The',
'Der Fuehrer\'s Face',
'Descendants, The',
'Descent',
'Desperate Living',
'Despicable Me',
'Despicable Me 2',
'Destry Rides Again',
'Deuce Bigalow: European Gigolo',
'Deuce Bigalow: Male Gigolo',
'Devil\'s Advocate, The',
'Devil\'s Own, The',
'Devil\'s Rejects, The',
'Devil in a Blue Dress',
'Devil Wears Prada, The',
'Defiance ',
'Dial M for Murder',
'Diary of a Wimpy Kid',
'Diary of a Wimpy Kid: Rodrick Rules',
'Diamonds Are Forever',
'Dick',
'Dick Tracy',
'Die Hard',
'Die Hard 2: Die Harder',
'Die Hard With a Vengeance',
'Live Free or Die Hard',
'Dinosaur',
'Dirty Dancing',
'Dirty Harry',
'Dirty Rotten Scoundrels',
'Dirty Shame, A',
'Dirty Work ',
'Disaster Movie',
'Disclosure',
'District 9',
'Disturbia',
'Disturbing Behavior',
'Divergent',
'Divine Secrets of the Ya Ya Sisterhood',
'Doctor Dolittle ',
'Doctor Dolittle ',
'Dr. Dolittle 2',
'Doctor Zhivago',
'Dodgeball: A True Underdog Story',
'Dodsworth',
'Dogma',
'Dogville',
'Dog Day Afternoon',
'Dolores Claiborne',
'Don Jon',
'Don Juan DeMarco ',
'Donald in Mathmagic Land',
'Donnie Brasco',
'Donnie Darko',
'Don\'t Be A Menace To South Central While Drinking Your Juice In The Hood',
'Don\'t Say a Word',
'Don\'t Tell Mom the Babysitter\'s Dead',
'Doom',
'Doors, The',
'Dorian Gray ',
'Double Indemnity ',
'Down Periscope',
'Down to Earth',
'Down With Love',
'Downfall ',
'Dr. No',
'Dr. Strangelove: Or How I Learned to Stop Worrying and Love the Bomb',
'Dracula ',
'Dracula ',
'Dracula ',
'Bram Stoker\'s Dracula ',
'Dracula A.D. 1972',
'Dracula: Dead and Loving It',
'Dracula: Prince of Darkness',
'Dracula\'s Daughter',
'Dragnet ',
'Dreamers, The',
'Driving Miss Daisy',
'Drop Dead Fred',
'Drop Dead Gorgeous',
'Drowning Mona',
'Drugstore Cowboy',
'Duck Soup',
'Dude, Where\'s My Car?',
'Duel ',
'Duel in the Sun',
'Dukes of Hazzard, The',
'Dumb and Dumber',
'Dumb and Dumber To',
'Dumb and Dumberer: When Harry Met Lloyd',
'Dumbo',
'Dummy',
'Dune',
'Duplex',
'Dylan Dog: Dead of Night',
'Earthquake',
'East of Eden',
'Eastern Promises',
'Easy A',
'Easy Rider',
'Ed Wood',
'Eddie and the Cruisers',
'Edge, The',
'Education, An',
'Edward Scissorhands',
'Eight Crazy Nights',
'Eight Legged Freaks',
'Eight Men Out',
'Election',
'Elf',
'Elizabeth',
'Elizabethtown',
'Elmer Gantry',
'Elvis ',
'Emperor\'s New Groove, The',
'Empire Records',
'Enchanted',
'End of Days',
'Enemy at the Gates',
'Enemy of the State',
'Englishman Who Went Up a Hill But Came Down a Mountain, The',
'English Patient, The',
'Enter the Dragon',
'Epic',
'Epic Movie',
'The Equalizer',
'Equilibrium',
'Eragon',
'Erin Brockovich',
'Ernest Goes to Camp',
'Ernest Goes to Jail',
'Ernest Saves Christmas',
'Ernest Scared Stupid',
'Escape from New York',
'E.T. the Extra-Terrestrial',
'Eternal Sunshine of the Spotless Mind',
'Eurotrip',
'Evan Almighty',
'Event Horizon',
'Ever After',
'Everything Is Illuminated',
'Everything You Always Wanted to Know About Sex* (*But Were Afraid to Ask)',
'Evil Dead, The',
'Evil Dead ',
'Evil Dead 2',
'Evolution',
'Excalibur',
'Exorcist, The',
'Exorcist III, The',
'Expelled: No Intelligence Allowed',
'An Extremely Goofy Movie',
'Eyes Wide Shut',
'Face in the Crowd, A',
'Face/Off',
'Factory Girl',
'Fahrenheit 451',
'Fahrenheit 9/11',
'Fail-Safe',
'Failure to Launch',
'Falling Down',
'Fame',
'Family Man, The',
'Fantastic Four',
'Fantastic Four: Rise of the Silver Surfer',
'Fantastic Mr. Fox',
'Fargo',
'Fast and Furious',
'Fast and Furious 6',
'Fast and the Furious, The',
'Fast and the Furious: Tokyo Drift, The',
'Fast, Cheap and Out of Control',
'Fast Five',
'Fast Times at Ridgemont High',
'Faster, Pussycat! Kill! Kill!',
'Fat Albert',
'Father of the Bride ',
'Fear and Loathing in Las Vegas',
'Fearless ',
'Femme Fatale',
'FernGully: The Last Rainforest',
'Ferris Bueller\'s Day Off',
'Few Good Men, A',
'Fiddler on the Roof',
'Field of Dreams',
'Fifth Element, The',
'Fight Club',
'Fighter, The',
'Final Destination',
'Final Destination 2',
'Final Destination 3',
'Final Destination, The',
'Final Destination 5',
'Final Fantasy: The Spirits Within',
'Final Fantasy VII: Advent Children',
'Finding Forrester',
'Finding Nemo',
'Finding Neverland',
'Fine Mess, A',
'Firestarter',
'Firm, The',
'First Blood',
'First Knight',
'First Wives Club, The',
'Fish Called Wanda, A',
'Fisher King, The',
'Fistful of Dollars, A',
'Five Easy Pieces',
'Five Minutes of Heaven',
'Flags of Our Fathers',
'Flash Gordon',
'Flatliners',
'Fletch',
'Fletch Lives aka Fletch 2',
'Flicka',
'Flipper ',
'Flubber',
'Flushed Away',
'Flyboys',
'Fog of War, The',
'Football Factory, The',
'Footloose ',
'Footloose ',
'Forbidden Kingdom, The',
'Forgetting Sarah Marshall',
'Forrest Gump',
'Fortune Cookie, The',
'Four Brothers',
'Four Weddings And A Funeral',
'Fountain, The',
'Fountainhead, The',
'Fox and the Hound, The',
'Fox and the Hound 2, The',
'Frankenstein ',
'Fracture',
'Frailty',
'Freaky Friday ',
'Freddy Got Fingered',
'Freddy vs. Jason',
'Free Willy',
'French Connection, The',
'Frenzy',
'Friday ',
'Friday Night Lights',
'Fried Green Tomatoes',
'Friends of Eddie Coyle, The',
'Friendly Persuasion',
'Fritz the Cat',
'From Dusk till Dawn',
'From Hell',
'From Here to Eternity',
'From Russia with Love',
'Frost/Nixon',
'Frozen ',
'Fuck',
'Fugitive, The',
'Full Metal Jacket',
'Furry Vengeance',
'Fury ',
'G-Force',
'Galaxy Quest',
'Game 6',
'Game, The',
'Game Plan, The',
'Gandhi',
'Gangs of New York',
'Garden State',
'Garfield',
'Garfield: A Tail of Two Kitties',
'Gaslight ',
'Gates of Heaven',
'Gattaca',
'Gentleman Prefer Blondes',
'George of the Jungle',
'Georgia Rule',
'Get Carter',
'Gettysburg',
'Get Shorty',
'Ghostbusters',
'Ghostbusters II',
'Ghost Dog: The Way of the Samurai',
'Ghost in the Shell 2: Innocence',
'Ghost Rider',
'Ghosts',
'Ghost World',
'G.I. Jane',
'G.I. Joe: Retaliation',
'Giant Claw, The',
'Girl, Interrupted',
'Girl Next Door, The',
'Girls Will Be Girls',
'Gladiator',
'Glen or Glenda',
'Glengarry Glen Ross',
'Glory',
'Glory Road',
'Gnomeo and Juliet',
'Go ',
'Godfather, The',
'Godfather, The: Part II',
'Godfather, The: Part III',
'Gods Must Be Crazy, The',
'Gone Baby Gone',
'Gone in 60 seconds',
'Gone with the Wind',
'Good Girl, The',
'Good Burger',
'Goodbye Girl, The',
'Good Bye Lenin!',
'Goodfellas',
'Good Luck Chuck',
'Good Morning, Vietnam',
'Good Night, and Good Luck.',
'Good Son, The',
'Good Will Hunting',
'Good Year, A',
'Good, the Bad and the Ugly, The',
'Goofy Movie, A',
'Goonies, The',
'Gosford Park',
'Gotti',
'Graduate, The',
'The Grand Budapest Hotel',
'Grand Canyon ',
'Grand Hotel',
'Grand Voyage, Le',
'Grandma\'s Boy',
'Grapes of Wrath, The ',
'Gravity',
'Great Dictator, The',
'Great Expectations',
'Grease',
'Grease 2',
'Great Debaters, The',
'Great Escape, The',
'The Great Mouse Detective',
'The Great Outdoors',
'The Greatest Game Ever Played',
'Green for Danger',
'Green Hornet, The',
'Green Lantern',
'Green Mile, The',
'Green Zone',
'Greenberg',
'Gremlins',
'Grey Zone, The',
'Grifters, The',
'Grindhouse',
'Groundhog Day',
'Grosse Pointe Blank',
'Grown Ups',
'Grumpy Old Men',
'Guardians of the Galaxy',
'Guarding Tess',
'Guess Who',
'Guess Who\'s Coming to Dinner',
'Gun Crazy',
'Gung Ho',
'Hackers',
'Hair',
'Hairspray  ',
'Halloween ',
'Halloween ',
'Halloween II ',
'Halloween II ',
'Halloween 4: The Return of Michael Myers ',
'Halloween 5: The Revenge of Michael Myers ',
'Halloween: The Curse of Michael Myers ',
'Half Baked',
'Hamlet 2',
'Hammett',
'Hancock',
'Hangover, The',
'Hangover Part II, The',
'Hannah and Her Sisters',
'Hannah Montana: The Movie',
'Hannibal',
'Hannibal Rising',
'Happening, The ',
'Happy Feet',
'Happy Feet Two',
'Happy Gilmore',
'Hard Boiled',
'Hard Candy',
'Hard Eight',
'Here Comes Pupcake',
'Hard Day\'s Night, A',
'Harold & Kumar Go to White Castle',
'Harold & Kumar Escape from Guantanamo Bay',
'Harold and Maude',
'Harry Potter and the Sorcerer\'s Stone',
'Harry Potter and the Chamber of Secrets',
'Harry Potter and the Prisoner of Azkaban',
'Harry Potter and the Goblet of Fire',
'Harry Potter and the Order of the Phoenix',
'Harry Potter and the Half-Blood Prince',
'Harry Potter and the Deathly Hallows – Part 1',
'Harry Potter and the Deathly Hallows – Part 2',
'Harvey',
'He\'s Just Not That Into You',
'He Died With A Felafel In His Hand',
'Heat ',
'Heartbreak Ridge',
'Heathers',
'Heavy Traffic‎',
'Heavyweights',
'Heist',
'Hellboy',
'Hellboy II: The Golden Army',
'Hellraiser',
'Hellbound: Hellraiser II',
'Hellraiser III: Hell on Earth',
'Hellraiser: Bloodline',
'Hellraiser: Inferno',
'Hellraiser: Hellseeker',
'Hellraiser: Deader',
'Hellraiser: Hellworld',
'Help!',
'Her',
'Herbie: Fully Loaded',
'Herbie Goes Bananas',
'Herbie Goes to Monte Carlo',
'Herbie Rides Again',
'Hercules ',
'Hero',
'Hey Good Lookin\'',
'Hide and Seek',
'High Fidelity',
'High Noon',
'Highlander (series)',
'High School Musical',
'High School Musical 2',
'High School Musical 3',
'High Road To China',
'The Hills Have Eyes ',
'The Hills Have Eyes 2',
'His Girl Friday',
'History Boys, The',
'History of the World: Part I',
'History of Violence, A',
'Hitch',
'Hitchhiker\'s Guide to the Galaxy, The',
'Hitler: The Rise of Evil',
'Hobbit: An Unexpected Journey, The',
'Hobbit: The Desolation of Smaug, The',
'Holes',
'Holiday, The',
'Holiday Inn',
'Hollywood Homicide',
'Hollywood Shuffle',
'Home Alone',
'Home Alone 2: Lost in New York',
'Home Alone 3',
'Home Alone 4',
'Home for the Holidays',
'Homeward Bound: The Incredible Journey',
'Homeward Bound II: Lost in San Francisco',
'Honey ',
'Honey, I Shrunk The Kids',
'Honeymoon in Vegas',
'Hoodwinked',
'Hoodwinked Too! Hood vs. Evil',
'Hook',
'Hoosiers',
'Horror Express',
'Horse Feathers',
'Hospital, The',
'Hostel ',
'Hostel: Part II',
'Hotel Rwanda',
'Hot Chick, The',
'Hot Fuzz',
'Hot Rod',
'Hot Shots!',
'Hot Shots! Part Deux',
'Hours, The',
'House Bunny, The',
'House on Haunted Hill ',
'How Green Was My Valley',
'How the Grinch Stole Christmas! (1966 cartoon TV movie)',
'How the Grinch Stole Christmas (2000 live-action movie)',
'How to Lose a Guy in 10 Days',
'How to Train Your Dragon',
'How to Train Your Dragon 2',
'Howard the Duck',
'Howl\'s Moving Castle',
'Howling, The',
'Hud',
'Hudsucker Proxy, The',
'Human Traffic',
'Hunchback of Notre Dame, The ',
'Hunchback of Notre Dame II, The ',
'Hunger Games, The',
'Hunt for Red October, The',
'Hurricane, The ',
'Hurt Locker, The',
'Hustler, The',
'I Am a Fugitive from a Chain Gang',
'I Am Legend',
'I Am Sam',
'I Heart Huckabees',
'I Know What You Did Last Summer',
'I Love You, Man',
'I Now Pronounce You Chuck and Larry',
'I, Robot',
'I Still Know What You Did Last Summer',
'Ice Age',
'Ice Age: The Meltdown',
'Ice Age: Dawn of the Dinosaurs',
'Ice Age: Continental Drift',
'Ice Princess',
'Identity Thief',
'Ides of March, The',
'Idiocracy',
'If....',
'If Only',
'Ikiru',
'Il Postino',
'Illusionist, The',
'Imagine Me & You',
'I\'m No Angel',
'I\'m Not There',
'Imitation Game, The',
'Impossible, The ',
'In & Out',
'In a Lonely Place',
'In Bruges',
'In Cold Blood',
'In the Heat of the Night',
'In the Line of Fire',
'In The Loop',
'Incredible Hulk, The',
'In Her Shoes',
'In the Mood for Love',
'In the Name of the Father',
'Into the Blue',
'Into the Wild',
'Inception',
'Incredibles, The',
'Inconvenient Truth, An',
'Independence Day',
'Inferno',
'Indiana Jones and the Kingdom of the Crystal Skull',
'Indiana Jones and the Last Crusade',
'Indiana Jones and the Temple of Doom',
'Inglorious Basterds',
'Innerspace',
'Inside Man',
'Inside Monkey Zetterland',
'Inspector Gadget',
'Inspector Gadget 2',
'Interview with the Vampire',
'Intolerable Cruelty',
'Invasion of the Body Snatchers ',
'Invasion of the Body Snatchers ',
'Inventing the Abbotts',
'Invictus',
'Iron Man',
'Iron Man 2',
'Iron Man 3',
'Iron Giant, The',
'Iron Jawed Angels',
'Island, The',
'Island of Dr. Moreau, The ',
'It\'s a Wonderful Life',
'It\'s a Mad, Mad, Mad, Mad World',
'It',
'It Conquered the World',
'It Happened One Night',
'Italian Job, The ',
'Italian Job, The ',
'Jack ',
'Jacket, The',
'Jack and Jill ',
'Jackie Brown',
'Jacob\'s Ladder',
'Jagged Edge',
'James and the Giant Peach',
'James Bond series',
'Jarhead',
'Jaws',
'Jaws 2',
'Jaws 3-D',
'Jay and Silent Bob Strike Back',
'Jeepers Creepers',
'Jefferson in Paris',
'Jennifer\'s Body',
'Jeremiah Johnson',
'Jerk, The',
'Jerry Maguire',
'JFK',
'Joe\'s Apartment',
'Joe Dirt',
'Joe Versus the Volcano',
'Johnny Dangerously',
'Johnny English',
'Johnny English Reborn',
'John Tucker Must Die',
'Joseph: King of Dreams',
'Joshua Tree ',
'Josie and the Pussycats',
'Journey 2: The Mysterious Island',
'Journey to the Center of the Earth ',
'Jude',
'Judgment at Nuremberg',
'Jumanji',
'Jumper',
'Junebug',
'Jungle 2 Jungle',
'Jungle Book, The ',
'Jungle Book 2, The',
'Jurassic Park',
'Jurassic Park: The Lost World',
'Jurassic Park 3',
'Just Friends',
'Just Like Heaven',
'Juwanna Mann',
'K-PAX',
'Kagemusha',
'Kalifornia',
'Kangaroo Jack',
'Karate Kid, The',
'Karate Kid, Part II, The',
'Karate Kid, Part III, The',
'Kate & Leopold',
'Kelly\'s Heroes',
'Kentucky Fried Movie, The',
'Key Largo ',
'Khuda Kay Liye',
'Kick-Ass',
'Kick-Ass 2',
'Kicking and Screaming ',
'Kicking & Screaming ',
'Kids Are All Right, The',
'Kill Bill: Volume 1',
'Kill Bill: Volume 2',
'Killer Klowns from Outer Space',
'Killers, The ',
'Killer Inside Me, The ',
'Killing Fields, The',
'Kindergarten Cop',
'Kind Hearts and Coronets',
'King Arthur',
'King Kong ',
'King Kong ',
'King of Comedy, The ',
'King\'s Speech, The',
'Kingdom of Heaven',
'Kingpin',
'Kinsey',
'Kiss Before Dying, A ',
'Kiss Kiss Bang Bang',
'Kiss Me Deadly',
'Kiss Tomorrow Goodbye ',
'Kite Runner, The',
'Klute',
'Knight and Day',
'Knight\'s Tale, A',
'Knocked Up',
'Knute Rockne, All American',
'Kramer vs. Kramer',
'Kung Fu Hustle',
'Kung Fu Panda',
'Kung Fu Panda 2',
'Kung Pow! Enter the Fist',
'Kurt Cobain: Montage of Heck',
'L. A. Confidential',
'La lengua de las mariposas',
'Labyrinth',
'Ladder 49',
'Lady and the Tramp',
'Lady and the Tramp II: Scamp\'s Adventure',
'Ladies Man, The',
'Lady Eve, The',
'Lady from Shanghai, The',
'Lady in the Water',
'Lady Vanishes, The ',
'Land of the Dead',
'Lara Croft: Tomb Raider',
'Lara Croft Tomb Raider: The Cradle of Life',
'L. A. Story',
'Last Action Hero',
'Last Boy Scout, The',
'Last Days of Disco, The',
'Last Detail, The',
'The Last House on the Left ',
'Last Man on Earth, The',
'The Last Mimzy',
'Last of the Mohicans, The',
'Last Picture Show, The',
'Last Samurai, The',
'Last Seduction, The',
'Last Starfighter, The',
'Last Unicorn, The',
'Laura',
'Latter Days',
'Lavender Hill Mob, The',
'Law Abiding Citizen',
'Lawrence of Arabia',
'Layer Cake',
'Legally Blonde',
'Legally Blonde 2: Red, White and Blonde',
'Lean on Me',
'League of Extraordinary Gentlemen, The',
'League of Their Own, A',
'Leaving Las Vegas',
'Legend',
'Legends of the Fall',
'Legend of the Guardians: The Owls of Ga\'Hoole',
'Legion ',
'Legend of 1900, The',
'Legend of Zorro, The',
'The Lego Movie',
'Lemony Snicket\'s A Series of Unfortunate Events',
'Lenny',
'Léon',
'Leroy & Stitch',
'Les Misérables ',
'Les Misérables ',
'Lesbian Vampire Killers',
'Let\'s Be Cops',
'Lethal Weapon',
'Lethal Weapon 2',
'Lethal Weapon 3',
'Lethal Weapon 4',
'The Letter',
'Letter from an Unknown Woman',
'Letters from Iwo Jima',
'Letters to Juliet',
'Liar, Liar',
'Libertine, The',
'Life of Brian',
'Life Aquatic with Steve Zissou, The',
'Life of David Gale, The',
'Life or Something Like It',
'Life Is Beautiful',
'Lifeboat',
'Lilo & Stitch',
'Lincoln ',
'Lion King, The',
'Lion King 1½, The',
'Lion King II: Simba\'s Pride, The',
'Liquid Sky',
'Little Big Man',
'Little Caesar',
'Little Children',
'Little Giants',
'Little Mermaid, The',
'Little Mermaid II: Return to the Sea, The',
'Little Miss Sunshine',
'Little Nicky',
'Little Princess, A (BBC)',
'Little Rascals, The',
'Little Shop of Horrors, The',
'Live Free or Die Hard',
'Live and Let Die',
'Lock, Stock and Two Smoking Barrels',
'Lolita',
'Lone Star',
'Long Kiss Goodnight, The',
'Long Goodbye, The',
'Longest Day, The',
'Looney Tunes: Back in Action',
'Looper',
'Lorax, The',
'Lord of the Rings: The Fellowship of the Ring, The',
'Lord of the Rings: The Return of the King, The',
'Lord of the Rings: The Two Towers, The',
'Lord of War',
'Lords of Dogtown',
'Lorenzo\'s Oil',
'Loser',
'Lost Boys, The',
'Lost Highway',
'Lost Horizon',
'Lost in Space',
'Lost in Translation',
'Lost Weekend, The',
'Lot Like Love, A',
'Love Actually',
'Love and Death',
'Love Bug, The',
'Love Guru, The',
'Love Me If You Dare',
'Love Story',
'Lovely Bones, The',
'Loving Annabelle',
'Lucas',
'Lucky Number Slevin',
'M',
'MacArthur',
'Mad Max',
'Mad Max 2: The Road Warrior',
'Mad Max III: Beyond Thunderdome',
'Madagascar ',
'Madagascar 3: Europe\'s Most Wanted',
'Madagascar: Escape 2 Africa',
'Madea: Family Reunion',
'Magnificent Ambersons, The',
'Magnificent Seven, The',
'Magnolia',
'Major League',
'Major Payne',
'Malcolm X',
'Mallrats',
'Maltese Falcon, The ',
'Mama ',
'Man for All Seasons, A ',
'Man in the Iron Mask, The',
'Man in the Moon, The',
'Man of the West',
'Man of the Year',
'Man on Fire',
'Man on the Moon',
'Man Who Fell To Earth',
'Man Who Shot Liberty Valance, The',
'Man Who Wasn\'t There, The',
'Man with Two Brains, The',
'Manchurian Candidate, The ',
'Manhattan',
'Manhattan Project, The',
'Manhunter',
'Mannequin',
'Manos: The Hands of Fate',
'Many Adventures of Winnie the Pooh, The',
'Margin Call',
'Margot at the Wedding',
'Marley & Me',
'Marnie',
'Martin and Lewis ',
'Marty',
'Mary and Max',
'Mary Poppins',
'MASH',
'Mask',
'Mask of Zorro, The',
'Master, The ',
'Master and Commander: The Far Side of the World',
'Masters of the Universe',
'Match Point',
'Matewan',
'Matilda',
'Matrix, The',
'Matrix Reloaded, The',
'Matrix Revolutions, The',
'Maverick',
'Max Keeble\'s Big Move',
'Max Payne',
'Me And You And Everyone We Know',
'Me, Myself & Irene',
'Mean Girls',
'Mean Machine',
'Mean Streets',
'Meaning of Life, The',
'Meatballs',
'Meet Dave',
'Meet Joe Black',
'Meet John Doe',
'Meet Me in St. Louis',
'Meet the Fockers',
'Meet the Parents',
'Meet the Robinsons',
'Meet the Spartans',
'Megamind',
'Melancholia',
'Melody ',
'Memento',
'Memoirs of a Geisha',
'Men in Black',
'Men in Black II',
'Men in Black 3',
'Men of Honor',
'Men Who Stare At Goats, The',
'Messenger, The ',
'Metropolitan',
'Miami Vice',
'Michael Clayton',
'Midnight Cowboy',
'Midnight Run',
'Midsummer Night\'s Dream, A ',
'Mighty Morphin Power Rangers: The Movie',
'Mighty Wind, A',
'Mike\'s New Car',
'Mildred Pierce',
'Milk',
'Millers Crossing',
'Million Dollar Baby',
'Million Dollar Hotel, The',
'Million Ways To Die In The West, A',
'Minority Report',
'Miracle',
'Miracle on 34th Street ',
'Miracle on 34th Street ',
'Mirrormask',
'Misery',
'Miss Congeniality',
'Miss Congeniality 2: Armed & Fabulous',
'Miss Pettigrew Lives for a Day',
'Missing',
'Mission: Impossible',
'Mission: Impossible II',
'Mission: Impossible III',
'Mission to Mars',
'Mississippi Burning',
'Mist, The',
'Mommie Dearest',
'Mona Lisa Smile',
'Money Pit, The',
'Money Talks',
'Moneyball',
'Mongol',
'Monsters, Inc.',
'Monsters University',
'Monsters vs. Aliens',
'Monty Python and the Holy Grail',
'Moon Child',
'Moonlight Mile',
'Moonrise Kingdom',
'Moonstruck',
'Motorcycle Diaries, The',
'Moulin Rouge!',
'MouseHunt',
'Movie 43',
'Mr. Brooks',
'Mr Death: The Rise & Fall of Fred A Leuchter Jr.',
'Mr. Deeds',
'Mr. Destiny',
'Mr. Holland\'s Opus',
'Mr. Magorium\'s Wonder Emporium',
'Mr. Mom',
'Mr. & Mrs. Smith',
'Mr. Peabody & Sherman',
'Mr. Smith Goes to Washington',
'Mrs. Doubtfire',
'Mrs. Miniver',
'Mud ',
'Mulan',
'Mulholland Dr.',
'Mulholland Falls',
'Multiple Maniacs',
'Mummy, The',
'Mummy Returns, The',
'Muppet Treasure Island',
'Muppets, The',
'Muppets from Space',
'Muppets Movie, The',
'Music and Lyrics',
'Mutiny on the Bounty ',
'Mutiny on the Bounty ',
'My Best Friend\'s Wedding',
'My Big Fat Greek Wedding',
'My Bloody Valentine 3D',
'My Blueberry Nights',
'My Cousin Vinny',
'My Dinner with Andre',
'My Fair Lady',
'My Favorite Year',
'My Girl',
'My Life Without Me',
'My Man Godfrey',
'My Own Private Idaho',
'My Sassy Girl',
'My Super Ex-Girlfriend',
'Mystery Men',
'Mystery of Mamo',
'Nacho Libre',
'Nadja',
'Naked',
'Naked City, The',
'Naked Gun, The',
'Napoleon Dynamite',
'Narc',
'Nanny McPhee',
'Nashville',
'National Lampoon\'s Animal House',
'National Lampoon\'s Christmas Vacation',
'National Lampoon\'s European Vacation',
'National Lampoon\'s Senior Trip',
'National Lampoon\'s Vacation',
'National Lampoon\'s Vegas Vacation',
'National Treasure',
'National Treasure: Book of Secrets',
'Natural, The',
'Natural Born Killers',
'Nausicaä of the Valley of the Wind',
'Nebraska',
'Negotiator, The',
'Net, The',
'Network',
'Never Been Kissed',
'Never Give a Sucker an Even Break',
'Never Let Me Go',
'NeverEnding Story, The',
'New Jack City',
'New Moon',
'New York, New York',
'Newsies',
'Next ',
'Next Karate Kid, The',
'Nice Dreams',
'Nicholas & Alexandra',
'Nick and Norah\'s Infinite Playlist',
'Night at the Museum',
'Night at the Museum: Battle of the Smithsonian',
'Night at the Opera, A',
'Night at The Roxbury, A',
'Night Moves',
'Night of the Hunter, The',
'Night Shift',
'Nightmare Before Christmas, The',
'Nightmare on Elm Street, A ',
'Nightmare on Elm Street, A ',
'Nightmare on Elm Street 2: Freddy\'s Revenge, A',
'Nightmare on Elm Street 3: Dream Warriors, A',
'Nightmare on Elm Street 4: The Dream Master, A',
'Nightmare on Elm Street 5: The Dream Child, A',
'Nim\'s Island',
'Nine Lives of Fritz the Cat, The',
'Nine to Five',
'Ninotchka',
'No Country for Old Men',
'No Way Out',
'Nobody\'s Fool',
'Norbit',
'North by Northwest',
'Not Another Teen Movie',
'Notebook, The',
'Nosferatu',
'Notes on a Scandal',
'Nothing to Lose',
'Notorious',
'Notting Hill',
'Now, Voyager',
'Number 23, The',
'Nutty Professor, The ',
'Nutty Professor 2',
'O Brother, Where Art Thou?',
'Object of My Affection, The',
'Ocean\'s Eleven ',
'Ocean\'s Thirteen',
'Ocean\'s Twelve',
'Office Space',
'Officer and a Gentleman, An',
'Oh, God! Book II',
'Oh, God! You Devil',
'Oklahoma! ',
'Oldboy',
'Old School',
'Oliver & Company',
'Omega Man, The',
'Omen, The ',
'Omen, The ',
'Omkara',
'On Golden Pond ',
'On Her Majesty\'s Secret Service',
'On Moonlight Bay',
'Once Upon a Time in America',
'Once Upon a Time in Mexico',
'Once Upon a Time in the West',
'Once Were Warriors',
'One Flew Over the Cuckoo\'s Nest',
'One Hundred and One Dalmatians',
'One Magic Christmas',
'Only You ',
'Open Season',
'Open Season 2',
'Opening of Misty Beethoven, The',
'Operation Dumbo Drop',
'Opposite of Sex, The',
'Orange County',
'Orgazmo',
'Original Sin',
'Orphan',
'Osmosis Jones',
'Other Guys, The',
'Other Boleyn Girl, The',
'Out of Sight',
'Out of the Past',
'Outbreak',
'Outlaw Josey Wales, The',
'Outside Providence',
'Outsiders, The',
'Over the Hedge',
'Oz the Great and Powerful',
'Pacifier, The',
'Pacific Rim',
'Pagemaster, The',
'Paparazzi',
'Paper Chase, The',
'Paradine Case, The',
'Parallax View, The',
'Parenthood',
'Party, The',
'Party Monster',
'Passion of the Christ, The',
'Patch Adams',
'Paths of Glory',
'Patriot, The',
'Patriot Games',
'Patton',
'Paul Blart: Mall Cop',
'Pawnbroker, The',
'Pay It Forward',
'Paycheck',
'PCU',
'Peaceful Warrior',
'Peacemaker, The',
'Pebble and the Penguin, The',
'Pee-wee\'s Big Adventure',
'Peggy Sue Got Married',
'Pelican Brief, The',
'Penelope',
'Penguins of Madagascar',
'People vs. Larry Flynt, The',
'Perfect Storm, The',
'Percy Jackson & the Olympians: The Lightning Thief',
'Perks of Being a Wallflower, The',
'Peter Pan ',
'Peter Pan ',
'Phantom of the Opera, The ',
'Phantom of the Paradise',
'Phenomenon',
'Philadelphia',
'Philadelphia Story, The ',
'Pi',
'Piano, The',
'Pillow Talk',
'Pineapple Express',
'Pink Floyd The Wall',
'Pink Flamingos',
'Pink Panther Strikes Again, The',
'Pinocchio ',
'Pinocchio 3000 ',
'Pirate Movie, The',
'Pirates of Penzance, The',
'Pirates of the Caribbean: At World\'s End',
'Pirates of the Caribbean: Dead Man\'s Chest',
'Pirates of the Caribbean: On Stranger Tides',
'Pirates of the Caribbean: The Curse of the Black Pearl',
'Pirate Radio (a.k.a. The Boat That Rocked)',
'Pirates Who Don\'t Do Anything: A VeggieTales Movie, The',
'Pitch Black',
'Pitch Perfect',
'Plan 9 from Outer Space',
'Planes',
'Planes: Fire & Rescue',
'Planes, Trains, and Automobiles',
'Planet 51',
'Planet of the Apes ',
'Planet of the Apes ',
'Platoon',
'Playing By Heart',
'Pleasantville',
'Pocahontas',
'Point Break',
'Pokemon',
'Polar Express, The',
'Police Academy',
'Poltergeist',
'Polyester',
'Ponette',
'Pooh\'s Grand Adventure: The Search for Christopher Robin',
'Pooh\'s Heffalump Movie',
'Pootie Tang',
'Popeye',
'Porco Rosso',
'Poseidon',
'Poseidon Adventure, The',
'Postman Always Rings Twice, The',
'Powder',
'Practical Magic',
'Precious: Based on the Novel "Push" by Sapphire',
'Predator',
'Predator 2',
'Prestige, The',
'Presumed Innocent',
'Pretty in Pink',
'Pretty Woman',
'Pride',
'Pride and Prejudice ',
'Primal Fear',
'Prince of Egypt, The',
'Prince of Persia: The Sands of Time',
'Princess and the Frog, The',
'Princess Bride, The',
'Princess Diaries, The',
'Princess Diaries 2, The: Royal Engagement',
'Princess Mononoke',
'Private Parts',
'Producers, The ',
'Producers, The ',
'Project X ',
'Prom Night ',
'Prometheus',
'Prophecy, The',
'Proposition, The',
'Protocol',
'Prozac Nation',
'Pursuit of Happyness, The',
'Psycho ',
'Psycho II',
'Psycho III',
'Psycho ',
'Public Enemies',
'Pulp Fiction',
'Punisher, The',
'Punisher: War Zone',
'Purple Rose of Cairo, The',
'Puss in Boots',
'Quadrophenia',
'Quarantine',
'Queen, The',
'Queen Christina',
'Queen of the Damned',
'Quest for Camelot',
'Quick and the Dead, The',
'Quiet Man, The',
'Quills',
'Quantum of Solace',
'Rabbit-Proof Fence',
'Racing Stripes',
'Radio Flyer',
'Rage: Carrie 2, The',
'Raging Bull',
'Raiders of the Lost Ark',
'Rain Man',
'Rainmaker, The ',
'Raising Arizona',
'Raising Helen',
'Ramayana: The Legend of Prince Rama',
'Rambo: First Blood Part II',
'Rambo III',
'Ransom ',
'Rapture, The',
'Rat Race',
'Ratatouille',
'Ray',
'Razor\'s Edge, The',
'The Reader',
'Real Genius',
'Reality Bites',
'Rear Window',
'Rebecca',
'Rebel Without a Cause',
'Rebound',
'REC 2',
'Red Eye',
'Red Dawn',
'Red Dragon',
'Red River',
'Red Rock West',
'Red Shoes, The',
'Reds',
'Reefer Madness‎',
'Reign of Fire',
'Reign Over Me',
'Religulous',
'Remember Me',
'Remember the Titans',
'Remo Williams: The Adventure Begins',
'Rent',
'Replacements, The',
'Repo! The Genetic Opera',
'Repo Man',
'Requiem for a Dream',
'The Rescuers',
'Rescuers Down Under, The',
'Reservoir Dogs',
'Resident Evil',
'Resident Evil: Apocalypse',
'Return of Jafar, The',
'Return of the Pink Panther, The',
'Return to Never Land',
'Return to the Blue Lagoon',
'Reversal of Fortune',
'Revolver',
'Red Tails',
'Riding the Bus with My Sister',
'Right Stuff, The',
'Ring, The',
'Ring Two, The',
'Rio',
'Ripley\'s Game',
'Rise of the Guardians',
'Rise of the Planet of the Apes',
'Rising Sun',
'Risky Business',
'Ritz, The',
'River Runs Through It, A',
'Road, The',
'Road House',
'Road to El Dorado, The',
'Road to Perdition',
'Road Warrior, The',
'Roaring Twenties, The',
'Robin Hood ',
'Robin Hood ',
'Robin Hood: Men in Tights',
'Robin Hood: Prince of Thieves',
'RoboCop',
'Robot Monster',
'Robots',
'Rock & Rule',
'Rock, The',
'Rock-a-Doodle',
'RockNRolla',
'Rocky',
'Rocky II',
'Rocky III',
'Rocky IV',
'Rocky V',
'Rocky Balboa',
'Rocky Horror Picture Show, The',
'Role Models',
'Roman Holiday',
'Romeo Must Die',
'Romy and Michele\'s High School Reunion',
'Room, The',
'Rope',
'Rosencrantz & Guildenstern Are Dead',
'Rosemary\'s Baby',
'Rounders',
'Royal Tenenbaums, The',
'Roxanne',
'Rudy',
'The Rugrats Movie',
'Rugrats in Paris: The Movie',
'Rugrats Go Wild',
'Rules of the Game, The',
'Ruling Class, The',
'Runaway Bride',
'Rundown, The',
'Running Man, The',
'Rush Hour',
'Rush Hour 2',
'Rush Hour 3',
'Rushmore',
'RV',
'S Club Seeing Double',
'Saboteur',
'Sabrina ',
'Sahara',
'Saint Joan',
'Salvador',
'Samurai X',
'Sands of Iwo Jima',
'Sandlot, The',
'Santa Claus: The Movie',
'Santa Clause, The',
'Santa Clause 2, The',
'Santa Clause 3: The Escape Clause, The',
'Saturday Night Fever',
'Savages, The',
'Saved!',
'Save the Last Dance',
'Saving Private Ryan',
'Saving Silverman',
'Saw ',
'Saw II',
'Saw III',
'Saw IV',
'Saw V',
'Saw VI',
'Saw 3D',
'Say Anything...',
'Scarface',
'Scary Movie',
'Scary Movie 2',
'Scary Movie 3',
'Scary Movie 4',
'Scary Movie 5',
'Scent of a Woman',
'Schindler\'s List',
'School of Rock',
'Science of Sleep, The',
'Scooby-Doo',
'Scooby-Doo 2: Monsters Unleashed',
'Scoop',
'Scott Pilgrim vs. the World',
'Scream ',
'Scream 2',
'Scream 3',
'Scream 4',
'Scrooged',
'Secondhand Lions',
'Serpico',
'Secret, The',
'Secret Garden, The ',
'Secret of NIHM, The',
'Secret of NIMH 2: Timmy to the Rescue, The',
'Secret Window',
'Semi-Pro',
'Sense and Sensibility',
'Serendipity',
'Serenity',
'Serial Mom',
'Se7en',
'Seven Samurai, The',
'Seventh Seal, The',
'Sex and the City: The Movie',
'Sex Drive',
'Sgt. Bilko',
'Shadow, The ',
'Shadowlands',
'Shaft\'s Big Score',
'Shaggy Dog, The ',
'Shakespeare in Love',
'Shallow Hal',
'Shark Tale',
'Shaun of the Dead',
'Shawshank Redemption, The',
'She\'s All That',
'She-Devil',
'She Done Him Wrong',
'Shenandoah',
'Sherlock Holmes ',
'Sherlock Holmes: A Game of Shadows',
'She\'s Out of My League',
'She\'s the Man',
'Shining, The',
'Sholay',
'Shoot \'Em Up',
'Short Circuit',
'Shot in the Dark, A',
'Shrek',
'Shrek 2',
'Shrek Forever After',
'Shrek the Third',
'Signs',
'Silence of the Lambs, The',
'Silver Linings Playbook',
'Simon Birch',
'Simpsons Movie, The',
'Sinbad: Legend of the Seven Seas',
'Sin City',
'Singin\' in the Rain',
'Singles',
'Sixteen Candles',
'Sixth Sense, The',
'Sinatra ',
'Sky Captain and the World of Tomorrow',
'Sky High',
'Slacker',
'Slap Her She\'s French',
'Slap Shot',
'SLC Punk!',
'Sleeping Beauty ',
'Sleeping with the Enemy',
'Sleepless in Seattle',
'Sleepy Hollow',
'Slumdog Millionaire',
'Sling Blade',
'Small Soldiers',
'Smokin\' Aces',
'Smurfs, The',
'Smurfs 2, The',
'Snatch',
'Snoopy, Come Home',
'Snow Dogs',
'Snow White and the Seven Dwarfs',
'Snowpiercer',
'So I Married an Axe Murderer',
'Soapdish',
'Something\'s Gotta Give',
'Something Wicked This Way Comes',
'Sometimes in April',
'Somewhere in Time',
'Songwriter',
'Sons of Eilaboun, the',
'Son of the Mask',
'Sophie\'s Choice',
'The Sorcerer\'s Apprentice ',
'Soul Plane',
'Soylent Green',
'Sound of Music, The',
'Southland Tales',
'Spaceballs',
'Space Chimps',
'Space Jam',
'Spartacus',
'Speed',
'Speed 2: Cruise Control',
'Spider-Man',
'Spider-Man 2',
'Spider-Man 3',
'Spirit: Stallion of the Cimarron',
'Splash',
'SpongeBob Movie: Sponge Out of Water, The',
'SpongeBob SquarePants Movie, The',
'Spy Hard',
'Stage Fright',
'Stagecoach ',
'Stand and Deliver',
'Stand by Me',
'Star is Born, A ',
'Stardust',
'Stargate',
'Star Trek ',
'Star Trek: The Motion Picture ',
'Star Trek II: The Wrath of Khan',
'Star Trek III: The Search for Spock',
'Star Trek IV: The Voyage Home',
'Star Trek V: The Final Frontier',
'Star Trek VI: The Undiscovered Country',
'Star Trek Generations',
'Star Trek: First Contact',
'Star Trek: Insurrection',
'Star Trek Nemesis',
'Star Wars Episode I: The Phantom Menace',
'Star Wars Episode II: Attack of the Clones',
'Star Wars Episode III: Revenge of the Sith',
'Star Wars Episode IV: A New Hope',
'Star Wars Episode V: The Empire Strikes Back',
'Star Wars Episode VI: Return of the Jedi',
'Star Wars: The Clone Wars',
'Starsky and Hutch',
'Starship Troopers',
'Stay Alive',
'Staying Alive',
'Steel Magnolias',
'Step Brothers',
'Step Up',
'Stepfather, The ',
'Stewie Griffin: The Untold Story',
'Sting, The',
'Strange Brew',
'Strange Days',
'Stranger, The ',
'Stranger than Fiction',
'Stripes',
'Striptease',
'Stuart Little',
'Stuart Little 2',
'Sucker Punch',
'Sunshine',
'Super',
'Superman Returns',
'Super Mario Bros.',
'Super Size Me',
'Super Troopers',
'Superbad',
'Superhero Movie',
'Superstar',
'Surf II',
'Surf\'s Up',
'Surrogates',
'Suspicion',
'The Swan Princess',
'S.W.A.T.',
'Sweeney Todd: The Demon Barber of Fleet Street',
'Sweetest Thing, The',
'Sweet Home Alabama',
'Swimming to Cambodia',
'Swimming with Sharks',
'Swingers',
'Swordfish',
'Sword in the Stone, The',
'Sydney White',
'Talented Mr. Ripley, The',
'Tall Tale',
'Talladega Nights: The Ballad of Ricky Bobby',
'Tamara',
'Tangled',
'Tao of Steve, The',
'Targets',
'Tarzan ',
'Tarzan II',
'Taxi',
'Taxi Driver',
'Teachers',
'Team America: World Police',
'Tears of the Black Tiger',
'Teenage Mutant Ninja Turtles',
'Teenage Mutant Ninja Turtles II: The Secret of the Ooze',
'Teenage Mutant Ninja Turtles III',
'Tenacious D in The Pick of Destiny',
'Terms of Endearment',
'Terminal, The',
'Terminator, The',
'Terminator 2: Judgment Day',
'Terminator 3: Rise of the Machines',
'Terminator Salvation',
'That Thing You Do!',
'Texas Chain Saw Massacre, The',
'The Texas Chainsaw Massacre ',
'The Texas Chainsaw Massacre: The Beginning',
'Thank You for Smoking',
'Thelma & Louise',
'There Will Be Blood',
'There\'s Something About Mary',
'The Mirror Has Two Faces',
'The Painted Veil',
'Thin Man, The',
'Thin Red Line, The ',
'Thing, The',
'Thing From Another World, The',
'Thirteen',
'Thirteen Days',
'This is Spinal Tap',
'This Is the End',
'Thomas Crown Affair, The',
'Thomas and the Magic Railroad',
'Thor',
'Thor: The Dark World',
'Thousand Clowns, A',
'Three Amigos',
'Three Days of the Condor',
'The Blob',
'The Ten Commandments',
'Three Little Pigs',
'Lone Ranger, The ',
'Three Musketeers, The ',
'Three Musketeers, The ',
'Three Musketeers, The ',
'The secret of their eyes',
'Thumbsucker',
'Thunderbolt and Lightfoot',
'Thunderbirds',
'THX 1138',
'Tiger Walks, A',
'Tigger Movie, The',
'Time Machine',
'Time To Kill, A',
'Tin Cup',
'Tinker Bell',
'Tinker Tailor Soldier Spy',
'Titan AE',
'Titanic ',
'Titanic ',
'TMNT',
'To Catch a Thief',
'To Have and Have Not',
'To Kill a Mockingbird',
'Tombstone',
'Tomb Raider',
'Tomcats',
'Tommy Boy',
'Tomorrow Never Dies',
'Tootsie',
'Top Gun',
'Top Secret',
'Topaz',
'Total Recall',
'Towering Inferno, The',
'Tower of Terror',
'Town, The ',
'Toxic Avenger, The',
'Toy Story',
'Toy Story 2',
'Toy Story 3',
'Trading Places',
'Traffic',
'Training Day',
'Trainspotting',
'Transamerica',
'Transformers: The Movie (Animated)',
'Transformers ',
'Transformers: Revenge of the Fallen',
'Transformers: Dark of the Moon',
'Transformers: Age of Extinction',
'Treasure of the Sierra Madre, The',
'Treasure Planet',
'Tremors',
'Tremors 2: Aftershocks',
'Trial, The ',
'Trick \'r Treat',
'Tristan and Isolde',
'Trixie',
'Troll',
'A Troll in Central Park',
'Tron',
'Tron: Legacy',
'Tropic Thunder',
'Troy',
'True Grit ',
'True Grit ',
'True Lies',
'True Romance',
'Truman Show, The',
'Tuck Everlasting',
'Twelve Monkeys',
'Twilight',
'The Twilight Saga: Breaking Dawn – Part 1',
'The Twilight Saga: Breaking Dawn - Part 2',
'The Twilight Saga: Eclipse',
'The Twilight Saga: New Moon',
'Twilight Zone: The Movie',
'Twister',
'Two Jakes, The',
'Two Moon Junction',
'Two Weeks Notice',
'UHF',
'Ultimate Gift, The',
'Ultraviolet',
'Unaccompanied Minors',
'Unbreakable',
'Uncle Buck',
'Under Siege',
'Under The Tuscan Sun',
'Undercover Brother',
'Underdog',
'Underworld ',
'Underworld: Evolution',
'Underworld: Rise of the Lycans',
'Unforgiven',
'Universal Soldier',
'United 93',
'United States of Leland, The',
'Untouchables, The',
'Unstoppable ',
'Up ',
'Up in the Air',
'Up the Down Staircase',
'Up in Smoke',
'Uptown Girls',
'Urban Cowboy',
'Urban Legend',
'U.S. Marshals',
'Usual Suspects, The',
'V for Vendetta',
'Valkyrie',
'Valley Girl',
'Vampires Suck',
'Van Helsing',
'Van Wilder',
'Vanilla Sky',
'Vampire in Brooklyn',
'Varsity Blues',
'Velvet Goldmine',
'Versus',
'Vertical Limit',
'VeggieTales: Gideon Tuba Warrior',
'VeggieTales: Moe and the Big Exit',
'VeggieTales: Tomato Sawyer and Huckleberry Larry\'s Big River Rescue',
'Verdict, The',
'Vertigo',
'Very Bad Things',
'Victor/Victoria',
'Vicky Cristina Barcelona',
'Videodrome',
'Village, The',
'Virgin Suicides, The',
'Volcano',
'Wag the Dog',
'Waiting for Guffman',
'Waking Life',
'Waiting...',
'Waitress',
'Walk Hard: The Dewey Cox Story',
'Walk the Line',
'Walk to Remember, A',
'WALL-E',
'Wall Street',
'Wallace & Gromit in The Curse of the Were-Rabbit',
'Wanted ',
'Wanted ',
'War and Peace',
'War, Inc.',
'War of the Worlds, The ',
'War of the Worlds ',
'WarGames',
'Warriors, The',
'Watcher, The',
'Watchmen',
'Waterboy, The',
'Waterloo ',
'Way Way Back, The',
'Wayne\'s World',
'Wayne\'s World 2',
'Way of the Gun, The',
'We Were Soldiers',
'Weather Man, The',
'Wedding Crashers',
'Wedding Date, The',
'Wedding Planner, The',
'Wedding Singer, The',
'Weird Science',
'Wes Craven\'s New Nightmare',
'West Side Story',
'Wet Hot American Summer',
'Whale Rider',
'What a Girl Wants',
'What About Bob?',
'What Dreams May Come',
'What Ever Happened to Baby Jane?',
'What Happens in Vegas',
'What Lies Beneath',
'What\'s Eating Gilbert Grape?',
'What\'s Up, Doc?',
'When a Man Loves a Woman',
'When a Stranger Calls ',
'When Harry Met Sally...',
'When in Rome ',
'While You Were Sleeping',
'Whiplash ',
'White Chicks',
'White Men Can\'t Jump',
'White Oleander',
'Who Framed Roger Rabbit',
'Who\'s Afraid of Virginia Woolf?',
'Whole Nine Yards, The',
'Wild Bunch, The',
'Wicker Man, The ',
'Wicker Man, The ',
'Wicker Park',
'Wild at Heart',
'Wild Hogs',
'Wild One, The',
'Willow',
'Willy Wonka & the Chocolate Factory',
'Windtalkers',
'Wings of Desire',
'Winnie the Pooh',
'Winter\'s Bone',
'Wishmaster',
'Wishmaster 2: Evil Never Dies',
'Witches of Eastwick, The',
'Withnail and I',
'Without a Paddle',
'Witness',
'The Wizard of Oz',
'Wolf Man, The',
'Wolf of Wall Street, The ',
'Wolverine, The',
'Woman in the Window, The',
'Woman of the Year',
'Wonder Boys',
'Working Girl',
'World Is Not Enough, The',
'World\'s Fastest Indian, The',
'Wrath of the Titans',
'Wreck-It Ralph',
'Wrestler, The',
'Wristcutters: A Love Story',
'Written on the Wind',
'Wrong Turn',
'Wyatt Earp',
'X Files: I Want to Believe, The',
'X Files: Fight The Future, The',
'X-Men',
'X2 (X-men 2)',
'X-Men: Days of Future Past',
'X-Men: First Class',
'X-men: The Last Stand',
'X-Men Origins: Wolverine',
'Xanadu',
'xXx',
'Y Tu Mamá También',
'Yankee Doodle Dandy‎',
'Year One',
'Yellow Submarine',
'Yes Man',
'Yojimbo',
'You Don\'t Mess with the Zohan',
'You Got Served',
'You, Me and Dupree',
'You Only Live Twice',
'Young and Innocent',
'Young Frankenstein',
'Young Guns',
'Young Guns II',
'Young Mr. Lincoln',
'Young Rajah, The',
'Your Friend the Rat (short)',
'Your Highness',
'Yours, Mine and Ours ',
'Yours, Mine and Ours ',
'Youth in Revolt',
'You\'ve Got Mail',
'Zack and Miri Make a Porno',
'Zardoz',
'Zathura',
'Zed & Two Noughts, A',
'Zelig',
'Zeitgeist: The Movie',
'Zenon: Girl of the 21st Century',
'Zero Day',
'Zodiac',
'Zombieland',
'Zoolander',
'Zorro, The Gay Blade',
'Zulu'
]
}